<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.quarkiverse</groupId>
        <artifactId>quarkiverse-parent</artifactId>
        <version>20</version>
    </parent>
    <groupId>io.quarkiverse.flow</groupId>
    <artifactId>quarkus-flow-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Quarkus Flow :: Parent</name>

    <modules>
        <module>core</module>
        <module>messaging</module>
        <module>langchain4j</module>
        <module>experimental</module>
    </modules>

    <scm>
        <connection>scm:git:git@github.com:quarkiverse/quarkus-flow.git</connection>
        <developerConnection>scm:git:git@github.com:quarkiverse/quarkus-flow.git</developerConnection>
        <url>https://github.com/quarkiverse/quarkus-flow</url>
      <tag>HEAD</tag>
  </scm>

    <properties>
        <compiler-plugin.version>3.14.1</compiler-plugin.version>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus.version>3.31.1</quarkus.version>
        <io.serverlessworkflow.version>7.10.0.Final</io.serverlessworkflow.version>
        <io.quarkiverse.jackson-jq.version>2.4.0</io.quarkiverse.jackson-jq.version>
        <io.quarkiverse.langchain4j.version>1.5.0</io.quarkiverse.langchain4j.version>
        <org.assertj.version>3.27.7</org.assertj.version>
        <io.cloudevents.version>4.0.1</io.cloudevents.version>
        <quarkus-antora.version>3.25.0</quarkus-antora.version>
        <mockserver.version>5.15.0</mockserver.version>
        <mockwebserver.version>5.3.2</mockwebserver.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-bom</artifactId>
                <version>${quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.serverlessworkflow</groupId>
                <artifactId>serverlessworkflow-bom</artifactId>
                <version>${io.serverlessworkflow.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.jackson-jq</groupId>
                <artifactId>quarkus-jackson-jq</artifactId>
                <version>${io.quarkiverse.jackson-jq.version}</version>
            </dependency>
            <dependency>
                <groupId>io.quarkiverse.jackson-jq</groupId>
                <artifactId>quarkus-jackson-jq-deployment</artifactId>
                <version>${io.quarkiverse.jackson-jq.version}</version>
            </dependency>
            <dependency>
                <groupId>io.cloudevents</groupId>
                <artifactId>cloudevents-json-jackson</artifactId>
                <version>${io.cloudevents.version}</version>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${org.assertj.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>io.quarkus</groupId>
                    <artifactId>quarkus-maven-plugin</artifactId>
                    <version>${quarkus.version}</version>
                </plugin>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${compiler-plugin.version}</version>
                    <configuration>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>io.quarkus</groupId>
                    <artifactId>quarkus-config-doc-maven-plugin</artifactId>
                    <version>${quarkus.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>net.revelc.code.formatter</groupId>
                <artifactId>formatter-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>format-code</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Import sorter -->
            <plugin>
                <groupId>net.revelc.code</groupId>
                <artifactId>impsort-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>sort-imports</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>sort</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>check-imports</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>docs</id>
            <activation>
                <property>
                    <name>performRelease</name>
                    <value>!true</value>
                </property>
            </activation>
            <modules>
                <module>docs</module>
                <module>examples</module>
            </modules>
        </profile>
    </profiles>
</project>
